name: pipeline

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: check
        uses: actions/checkout@v4

      - name: copy
        run: |
          done=${{  github.ref_name }}
          mkdir -p "./pages/${done}"
          cp -r ./eng "./pages/${done}/"
          cp -r ./ru "./pages/${done}/"
          cp -r ./index.html "./pages/${done}/"
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./pages
           keep_files: true
