name: pipeline

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: check
        uses: actions/checkout@v4

      - name: copy
        run: |
          VERSION=${{  github.ref_name }}
          mkdir -p "./done/${directory}"
          cp -r ./eng "./done/${directory}/"
          cp -r ./ru "./done/${directory}/"
          cp -r ./index.html "./done/${directory}/"
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./done
           keep_files: true
